name: Build and deploy

on:
  push:
    branches: [ main ]
    
  # Run workflow manually
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout repository
        uses: action/checkout@main
      - name: Install dependecies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: action/upload-artifact@main
        with:
          name: dist
          path: dist
deploy:
  name: Deploy
  needs: build
  runs-on: ubuntu-lastest
  steps:
    - name: Checkout repository
      uses: action/checkout@main
    - name: Dowload artifact
      uses: action/dowload-artifact@main
      with:
        name: dist
        path: dist
    - name: Deploy to Firebase
      uses: w9jds/firebase-acttion@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secret.FIREBASE_TOKEN}}
        
      
      
      
    
    
